[project]
name = "p2m"
version = "0.1.0"
description = ""
authors = [
    {name = "Augustin Morval",email = "augustin.morval.pro@gmail.com"},
    {name = "Mathieu Jayet",email = "mathieu.jayet@gmail.com"},
    {name = "Jérémy Pahler",email = "jeremy.pahler@gmail.com"},
]
requires-python = ">=3.10"
dependencies = [
    "opencv-python (>=4.11.0.86,<5.0.0.0)",
    "imutils (>=0.5.4,<0.6.0)",
    "numpy (>=2.2.3,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
